-- Create databases for container
CREATE DATABASE auth_db OWNER fitsupply;
CREATE DATABASE catalog_db OWNER fitsupply;
CREATE DATABASE inventory_db OWNER fitsupply;
CREATE DATABASE order_db OWNER fitsupply;
CREATE DATABASE cart_db OWNER fitsupply;
CREATE DATABASE payment_db OWNER fitsupply;
CREATE DATABASE shipping_db OWNER fitsupply;
CREATE DATABASE notification_db OWNER fitsupply;
