services:
  api-gateway:
    build:
      context: ./apps/api-gateway
    container_name: api-gateway
    environment:
      PORT: 3000
      AUTH_SERVICE_URL: http://auth-service:3001
    ports:
      - "3000:3000"
    depends_on:
      - auth-service

  auth-service:
    build:
      context: ./apps/auth-service
    container_name: auth-service
    environment:
      PORT: 3001
    ports:
      - "3001:3001"

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: fitsupply
      POSTGRES_USER: fitsupply
      POSTGRES_PASSWORD: fitsupply
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  catalog-service:
    build:
      context: ./apps/catalog-service
    container_name: catalog-service
    environment:
      PORT: 3002
      DATABASE_URL: postgres://fitsupply:fitsupply@postgres:5432/fitsupply
    ports:
      - "3002:3002"
    depends_on:
      - postgres

  order-service:
    build:
      context: ./apps/order-service
    container_name: order-service
    environment:
      PORT: 3003
      DATABASE_URL: postgres://fitsupply:fitsupply@postgres:5432/fitsupply
    ports:
      - "3003:3003"
    depends_on:
      - postgres

volumes:
  postgres_data:
