services:
  api-gateway:
    build:
      context: ./apps/api-gateway
    container_name: api-gateway
    environment:
      PORT: 3000
      AUTH_SERVICE_URL: http://auth-service:3001
      CATALOG_SERVICE_URL: http://catalog-service:3002
      ORDER_SERVICE_URL: http://order-service:3003
    ports:
      - "3000:3000"
    volumes:
      - ./apps/api-gateway/src:/app/src
      - /app/node_modules  
    command: npm run dev
    stdin_open: true
    tty: true
    depends_on:
      - auth-service
      - catalog-service
      - order-service

  auth-service:
    build:
      context: ./apps/auth-service
    container_name: auth-service
    env_file:
      - ./apps/auth-service/.env
    ports:
      - "3001:3001"
    volumes:
      - ./apps/auth-service/src:/app/src
      - ./apps/auth-service/prisma:/app/prisma
      - /app/node_modules  
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"
    stdin_open: true
    tty: true
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: fitsupply
      POSTGRES_USER: fitsupply
      POSTGRES_PASSWORD: fitsupply
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fitsupply -d fitsupply"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init-multiple-dbs.sql:/docker-entrypoint-initdb.d/init-multiple-dbs.sql
    ports:
      - "5433:5432"

  catalog-service:
    build:
      context: ./apps/catalog-service
    container_name: catalog-service
    environment:
      PORT: 3002
      DATABASE_URL: postgres://fitsupply:fitsupply@postgres:5432/catalog_db
    ports:
      - "3002:3002"
    volumes:
      - ./apps/catalog-service/src:/app/src
      - /app/node_modules  
    command: npm run dev
    stdin_open: true
    tty: true
    depends_on:
      postgres:
        condition: service_healthy


  order-service:
    build:
      context: ./apps/order-service
    container_name: order-service
    environment:
      PORT: 3003
      DATABASE_URL: postgres://fitsupply:fitsupply@postgres:5432/order_db
    ports:
      - "3003:3003"
    volumes:
      - ./apps/order-service/src:/app/src
      - /app/node_modules  
    command: npm run dev
    stdin_open: true
    tty: true
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
