@baseUrl = http://localhost:3001
@contentType = application/json

### Register
POST {{baseUrl}}/register
Content-Type: {{contentType}}

{
  "email": "customer123e@example.com",
  "password": "Password123!",
  "name": "Customer123 One"
}

### Login
# @name login
POST {{baseUrl}}/login
Content-Type: {{contentType}}

{
  "email": "customer123e@example.com",
  "password": "Password123!"
}

###

@accessToken = {{login.response.body.accessToken}}
@refreshToken = {{login.response.body.refreshToken}}

### Refresh token
POST {{baseUrl}}/refresh-token
Content-Type: {{contentType}}

{
  "refreshToken": "{{refreshToken}}"
}

### Get JWKS
GET {{baseUrl}}/jwks

### Logout
POST {{baseUrl}}/logout
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "refreshToken": "{{refreshToken}}"
}