@gatewayBaseUrl = http://localhost:3000
@contentType = application/json

### Login via gateway
# @name login
POST {{gatewayBaseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "email": "customer123e@example.com",
  "password": "Password123!"
}

###

@accessToken = {{login.response.body.accessToken}}

### Inventory service health
GET {{gatewayBaseUrl}}/health
x-internal-secret: FitSupply_Internal_Secret_2026

### Create inventory via gateway
# @name createInventory
POST {{gatewayBaseUrl}}/inventory
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "productId": "product-id-1",
  "stock": 100,
  "lowStockThreshold": 10
}

###

### Get inventory by productId via gateway
GET {{gatewayBaseUrl}}/inventory/products/product-id-1
Authorization: Bearer {{accessToken}}

### Patch inventory by productId via gateway
PATCH {{gatewayBaseUrl}}/inventory/products/product-id-1
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "stock": 120,
  "lowStockThreshold": 15
}

### Batch inventory lookup via gateway
POST {{gatewayBaseUrl}}/inventory/products/batch
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "productIds": ["product-id-1", "id2", "id3"]
}

### Adjust inventory via gateway
POST {{gatewayBaseUrl}}/inventory/products/product-id-1/adjust
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "quantity": -20,
  "reason": "RESTOCK"
}
